"""
observability/ab_testing.py — A/B Testing for Grounding Prompts

Manages two prompt variants:
  v1 — Current/standard grounding prompt (same as existing ANSWER_PROMPT)
  v2 — Stricter grounding prompt that:
         • Demands verbatim evidence before answering
         • Refuses when context is insufficient (explicit refusal policy)
         • Adds stronger anti-hallucination language

Assignment is random (50/50) per query. The assigned variant is passed
back to the LLMLogger so every log record carries the prompt_version field.

Comparison helpers aggregate metrics by version for the Streamlit dashboard.
"""

import logging
import random
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from langchain_core.prompts import ChatPromptTemplate

logger = logging.getLogger(__name__)

# ── Prompt Variants ───────────────────────────────────────────────────────────

PROMPT_V1_SYSTEM = """You are BVRIT College Information Assistant, an AI assistant designed to answer questions about BVRIT College using the college knowledge base and available tools.

## CRITICAL INSTRUCTIONS

1. You will receive a Retrieved Context below the user's question. This context comes from the college's official knowledge base document.

2. **You MUST answer the question using the Retrieved Context.** The context IS the college's knowledge base. If the context contains information related to the question, use it to formulate an answer.

3. **NEVER say "I couldn't find this information" if the Retrieved Context has any information relevant to the question.** Even partial or indirect information should be used.

4. **You have tools available!** Use them when needed:
   - `fee_calculator`: For ANY math involving fees, tuition, scholarships, or costs.
   - `date_checker`: For ANY question about dates, deadlines, or how many days remain.
   - `percentage_calculator`: For ANY percentage calculations.

5. Include citations in [Section Name] format for every piece of information you use.

6. Be concise and helpful.

## AI DISCLOSURE
You are an AI assistant. For critical decisions (admissions, finances, legal), always verify with the BVRIT admissions office directly.
"""

PROMPT_V2_SYSTEM = """You are BVRIT College Information Assistant — a strictly grounded AI assistant.

## STRICT GROUNDING RULES (FOLLOW WITHOUT EXCEPTION)

1. **EVIDENCE-FIRST POLICY**: Before answering, locate the exact passage in the Retrieved Context that supports your answer. Quote or paraphrase it directly. Never infer or extrapolate beyond what the context explicitly states.

2. **MANDATORY REFUSAL**: If the Retrieved Context does NOT contain information that directly answers the question, you MUST respond with:
   "I don't have specific information about [topic] in my knowledge base. Please contact BVRIT directly at [contact details from context if available]."
   Do NOT guess, speculate, or use general knowledge.

3. **CITATION REQUIRED**: Every factual claim MUST be followed by a [Section Name] citation. Uncited claims are forbidden.

4. **TOOL MANDATE**: For any numerical calculation (fees, dates, percentages), you MUST use the provided tools. Performing calculations yourself is forbidden.

5. **SCOPE LIMIT**: Answer ONLY about BVRIT College. For unrelated topics, respond:
   "I can only answer questions about BVRIT College."

6. **HALLUCINATION PREVENTION**: If you are uncertain about any detail, explicitly say so and direct the user to verify with the institution.

## AI DISCLOSURE
You are an AI assistant subject to limitations. For critical decisions (admissions, finances), verify all information with the BVRIT admissions office.

## TRANSPARENCY
This response was generated by an AI using the college's knowledge base document. The information may not reflect the most recent updates.
"""

# Human message template (shared between v1 and v2)
_HUMAN_TEMPLATE = """User Question: {question}

Retrieved Context:
{context}

Instructions: Answer strictly using the Retrieved Context above. Include [Section Name] citations for all facts.
"""


def build_v1_prompt() -> ChatPromptTemplate:
    """Return the standard (v1) ChatPromptTemplate."""
    from langchain_core.prompts import MessagesPlaceholder
    return ChatPromptTemplate.from_messages(
        [
            ("system", PROMPT_V1_SYSTEM),
            MessagesPlaceholder(variable_name="chat_history"),
            ("human", _HUMAN_TEMPLATE),
        ]
    )


def build_v2_prompt() -> ChatPromptTemplate:
    """Return the stricter (v2) ChatPromptTemplate."""
    from langchain_core.prompts import MessagesPlaceholder
    return ChatPromptTemplate.from_messages(
        [
            ("system", PROMPT_V2_SYSTEM),
            MessagesPlaceholder(variable_name="chat_history"),
            ("human", _HUMAN_TEMPLATE),
        ]
    )


# ── A/B Manager ───────────────────────────────────────────────────────────────

class ABTestManager:
    """
    Randomly assigns prompt variants and tracks aggregate metrics.

    Usage::

        ab = ABTestManager()

        # Get the system prompt text for this call
        version, system_text = ab.assign_variant()

        # After the call completes, record its outcome
        ab.record_result(
            version=version,
            latency=2.1,
            cost=0.0002,
            refusal=False,
            citations=["Admissions", "Fees"],
            success=True,
        )

        # Get comparison stats
        report = ab.compare()
    """

    def __init__(self, seed: Optional[int] = None) -> None:
        """
        Args:
            seed: Optional RNG seed for reproducible assignment (useful in tests).
        """
        self._rng = random.Random(seed)
        # Per-version accumulators
        self._stats: Dict[str, Dict] = {
            "v1": self._empty_bucket(),
            "v2": self._empty_bucket(),
        }

    # ── Assignment ────────────────────────────────────────────────────────────

    def assign_variant(self) -> Tuple[str, str]:
        """
        Randomly assign a prompt variant for this query (50/50 split).

        Returns:
            Tuple of (version_string, system_prompt_text).
            version_string is "v1" or "v2".
        """
        version = self._rng.choice(["v1", "v2"])
        system_text = PROMPT_V1_SYSTEM if version == "v1" else PROMPT_V2_SYSTEM
        logger.debug(f"A/B assigned prompt version: {version}")
        return version, system_text

    # ── Result recording ──────────────────────────────────────────────────────

    def record_result(
        self,
        version: str,
        latency: float,
        cost: float,
        refusal: bool,
        citations: List[str],
        success: bool,
    ) -> None:
        """
        Accumulate metrics for the given prompt version.

        Args:
            version:   "v1" or "v2"
            latency:   Call latency in seconds.
            cost:      Estimated cost in USD.
            refusal:   True if the LLM refused to answer.
            citations: List of citation strings in the response.
            success:   Whether the call completed without error.
        """
        if version not in self._stats:
            logger.warning(f"ABTestManager: unknown version '{version}'")
            return

        bucket = self._stats[version]
        bucket["calls"] += 1
        bucket["total_latency"] += latency
        bucket["total_cost"] += cost
        bucket["refusals"] += int(refusal)
        bucket["citations_total"] += len(citations)
        bucket["errors"] += int(not success)

    # ── Comparison ────────────────────────────────────────────────────────────

    def compare(self) -> Dict[str, Dict]:
        """
        Return a comparison report of both prompt variants.

        Returns:
            Dict keyed by "v1" and "v2", each containing:
              calls, avg_latency_s, avg_cost_usd, refusal_rate,
              avg_citations, error_rate
        """
        report: Dict[str, Dict] = {}
        for version, bucket in self._stats.items():
            n = bucket["calls"] or 1  # avoid div/0
            report[version] = {
                "calls": bucket["calls"],
                "avg_latency_s": round(bucket["total_latency"] / n, 3),
                "avg_cost_usd": round(bucket["total_cost"] / n, 6),
                "refusal_rate": round(bucket["refusals"] / n, 4),
                "avg_citations": round(bucket["citations_total"] / n, 2),
                "error_rate": round(bucket["errors"] / n, 4),
            }
        return report

    def get_version_counts(self) -> Dict[str, int]:
        """Return {version: call_count} for quick display."""
        return {v: self._stats[v]["calls"] for v in self._stats}

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _empty_bucket() -> Dict:
        return {
            "calls": 0,
            "total_latency": 0.0,
            "total_cost": 0.0,
            "refusals": 0,
            "citations_total": 0,
            "errors": 0,
        }


# Module-level singleton
ab_test_manager = ABTestManager()
